# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'macOS-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      # npm run test:ci
    displayName: 'install, lint, unit test, e2e test'

  - task: PublishPipelineArtifact@0
    displayName: 'Publish Screenshots (Cypress)'
    condition: failed()
    inputs:
      artifactName: 'screenshots'
      targetPath: '$(Build.SourcesDirectory)/cypress/screenshots'

  - task: PublishPipelineArtifact@0
    displayName: 'Publish Videos (Cypress)'
    condition: failed()
    inputs:
      artifactName: 'videos'
      targetPath: '$(Build.SourcesDirectory)/cypress/videos'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: '**/*junit.xml'

  - script: |
      npm run build
    displayName: 'build'

  - task: PublishPipelineArtifact@0
    condition: succeeded()
    displayName: 'Publish `npm run build` result'
    inputs:
      artifactName: 'build'
      targetPath: 'build'
  
  - script: |
      git config user.email "chui.hinwai+azure@gmail.com" 
      git config user.name "Azure"
      npm run deploy -- -r https://$(github_pat)@github.com/EdmondChuiHW/email-contact.git
